/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for ABBREVIATED_END Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class ABBREVIATED_END extends Token {
    public ABBREVIATED_END(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
