/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for ALT_GE Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class ALT_GE extends Token {
    public ALT_GE(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
