/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for ALT_LE Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class ALT_LE extends Token {
    public ALT_LE(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
