/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for C_IDENTIFIER Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class C_IDENTIFIER extends Token {
    public C_IDENTIFIER(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
