/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for CLOSE_CURLY Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class CLOSE_CURLY extends Token {
    public CLOSE_CURLY(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
