/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for ElseIfSection AST Node type
  * by the ASTNode.java.ftl template
  */
package qute.ast;

import qute.*;
@SuppressWarnings("unused")
public class ElseIfSection extends BaseNode {
}
