/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for FOR Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class FOR extends Token {
    public FOR(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
