/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for GE Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class GE extends Token {
    public GE(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
