/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for NullLiteral AST Node type
  * by the ASTNode.java.ftl template
  */
package qute.ast;

import qute.*;
@SuppressWarnings("unused")
public class NullLiteral extends BaseNode {
}
