/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for NumberLiteral2 Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class NumberLiteral2 extends Literal {
    public NumberLiteral2(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
