/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for OPEN_COMMENT Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class OPEN_COMMENT extends Token {
    public OPEN_COMMENT(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
