/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for OR2 Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class OR2 extends Token {
    public OR2(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
