/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for PositionalArgsList AST Node type
  * by the ASTNode.java.ftl template
  */
package qute.ast;

import qute.*;
@SuppressWarnings("unused")
public class PositionalArgsList extends BaseNode {
}
