/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for QUTE_INCLUDE Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class QUTE_INCLUDE extends Token {
    public QUTE_INCLUDE(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
