/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for RAW_STRING Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class RAW_STRING extends Token {
    public RAW_STRING(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
