/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for START_SECTION Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class START_SECTION extends Token {
    public START_SECTION(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
