/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for START_PARAMETER_DECL Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class START_PARAMETER_DECL extends Token {
    public START_PARAMETER_DECL(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
