/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for STRING_LITERAL Token subclass
  * by the ASTToken.java.ftl template
  */
package qute.ast;

import qute.*;
import qute.QUTEConstants.TokenType;
@SuppressWarnings("unused")
public class STRING_LITERAL extends Token {
    public STRING_LITERAL(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
