/* Generated by: JavaCC 21 Parser Generator. Do not edit. ABBREVIATED_END.java */
package qute;

@SuppressWarnings("unused")
public class ABBREVIATED_END extends Token {
    public ABBREVIATED_END(TokenType type,String image) {
        super(type,image);
    }

}
