/* Generated by: JavaCC 21 Parser Generator. Do not edit. ABBREVIATED_END.java */
package qute;

public class ABBREVIATED_END extends Token {
    public ABBREVIATED_END(int kind,String image) {
        super(kind,image);
    }

}
