/* Generated by: JavaCC 21 Parser Generator. Do not edit. ALT_GE.java */
package qute;

@SuppressWarnings("unused")
public class ALT_GE extends Token {
    public ALT_GE(TokenType type,String image) {
        super(type,image);
    }

}
