/* Generated by: JavaCC 21 Parser Generator. Do not edit. ALT_LE.java */
package qute;

@SuppressWarnings("unused")
public class ALT_LE extends Token {
    public ALT_LE(TokenType type,String image) {
        super(type,image);
    }

}
