/* Generated by: JavaCC 21 Parser Generator. Do not edit. ALT_LT.java */
package qute;

@SuppressWarnings("unused")
public class ALT_LT extends Token {
    public ALT_LT(int kind,String image) {
        super(kind,image);
    }

}
