/* Generated by: JavaCC 21 Parser Generator. Do not edit. ALT_GT.java */
package qute;

@SuppressWarnings("unused")
public class ALT_GT extends Token {
    public ALT_GT(int kind,String image) {
        super(kind,image);
    }

}
