/* Generated by: JavaCC 21 Parser Generator. Do not edit. ALT_LT.java */
package qute;

@SuppressWarnings("unused")
public class ALT_LT extends Token {
    public ALT_LT(TokenType type,String image) {
        super(type,image);
    }

}
