/* Generated by: JavaCC 21 Parser Generator. Do not edit. AND.java */
package qute;

@SuppressWarnings("unused")
public class AND extends Token {
    public AND(TokenType type,String image) {
        super(type,image);
    }

}
