/* Generated by: JavaCC 21 Parser Generator. Do not edit. AND2.java */
package qute;

@SuppressWarnings("unused")
public class AND2 extends Token {
    public AND2(TokenType type,String image) {
        super(type,image);
    }

}
