/* Generated by: JavaCC 21 Parser Generator. Do not edit. AS.java */
package qute;

@SuppressWarnings("unused")
public class AS extends Token {
    public AS(int kind,String image) {
        super(kind,image);
    }

}
