/* Generated by: JavaCC 21 Parser Generator. Do not edit. C_IDENTIFIER.java */
package qute;

@SuppressWarnings("unused")
public class C_IDENTIFIER extends Token {
    public C_IDENTIFIER(int kind,String image) {
        super(kind,image);
    }

}
