/* Generated by: JavaCC 21 Parser Generator. Do not edit. CLOSE_CURLY.java */
package qute;

@SuppressWarnings("unused")
public class CLOSE_CURLY extends Token {
    public CLOSE_CURLY(TokenType type,String image) {
        super(type,image);
    }

}
