/* Generated by: JavaCC 21 Parser Generator. Do not edit. CLOSE_BRACKET.java */
package qute;

@SuppressWarnings("unused")
public class CLOSE_BRACKET extends Token {
    public CLOSE_BRACKET(TokenType type,String image) {
        super(type,image);
    }

}
