/* Generated by: JavaCC 21 Parser Generator. Do not edit. CLOSE_BRACKET.java */
package qute;

@SuppressWarnings("unused")
public class CLOSE_BRACKET extends Token {
    public CLOSE_BRACKET(int kind,String image) {
        super(kind,image);
    }

}
