/* Generated by: JavaCC 21 Parser Generator. Do not edit. CLOSE_EMPTY.java */
package qute;

@SuppressWarnings("unused")
public class CLOSE_EMPTY extends Token {
    public CLOSE_EMPTY(TokenType type,String image) {
        super(type,image);
    }

}
