/* Generated by: JavaCC 21 Parser Generator. Do not edit. CLOSE_CURLY.java */
package qute;

public class CLOSE_CURLY extends Token {
    public CLOSE_CURLY(int kind,String image) {
        super(kind,image);
    }

}
