/* Generated by: JavaCC 21 Parser Generator. Do not edit. Comment.java */
package qute;

@SuppressWarnings("unused")
public class Comment extends Token {
    public Comment(int kind,String image) {
        super(kind,image);
    }

}
