/* Generated by: JavaCC 21 Parser Generator. Do not edit. COMMA.java */
package qute;

@SuppressWarnings("unused")
public class COMMA extends Token {
    public COMMA(TokenType type,String image) {
        super(type,image);
    }

}
