/* Generated by: JavaCC 21 Parser Generator. Do not edit. COMMA.java */
package qute;

@SuppressWarnings("unused")
public class COMMA extends Token {
    public COMMA(int kind,String image) {
        super(kind,image);
    }

}
