/* Generated by: JavaCC 21 Parser Generator. Do not edit. DECIMAL.java */
package qute;

@SuppressWarnings("unused")
public class DECIMAL extends Token {
    public DECIMAL(TokenType type,String image) {
        super(type,image);
    }

}
