/* Generated by: JavaCC 21 Parser Generator. Do not edit. DECIMAL.java */
package qute;

@SuppressWarnings("unused")
public class DECIMAL extends Token {
    public DECIMAL(int kind,String image) {
        super(kind,image);
    }

}
