/* Generated by: JavaCC 21 Parser Generator. Do not edit. Delimiter.java */
package qute;

@SuppressWarnings("unused")
public class Delimiter extends Token {
    public Delimiter(TokenType type,String image) {
        super(type,image);
    }

}
