/* Generated by: JavaCC 21 Parser Generator. Do not edit. Delimiter.java */
package qute;

@SuppressWarnings("unused")
public class Delimiter extends Token {
    public Delimiter(int kind,String image) {
        super(kind,image);
    }

}
