/* Generated by: JavaCC 21 Parser Generator. Do not edit. DIVIDE.java */
package qute;

@SuppressWarnings("unused")
public class DIVIDE extends Token {
    public DIVIDE(TokenType type,String image) {
        super(type,image);
    }

}
