/* Generated by: JavaCC 21 Parser Generator. Do not edit. DOT.java */
package qute;

@SuppressWarnings("unused")
public class DOT extends Token {
    public DOT(TokenType type,String image) {
        super(type,image);
    }

}
