/* Generated by: JavaCC 21 Parser Generator. Do not edit. DOT_DOT.java */
package qute;

@SuppressWarnings("unused")
public class DOT_DOT extends Token {
    public DOT_DOT(int kind,String image) {
        super(kind,image);
    }

}
