/* Generated by: JavaCC 21 Parser Generator. Do not edit. EACH.java */
package qute;

@SuppressWarnings("unused")
public class EACH extends Token {
    public EACH(int kind,String image) {
        super(kind,image);
    }

}
