/* Generated by: JavaCC 21 Parser Generator. Do not edit. ELSEIF.java */
package qute;

@SuppressWarnings("unused")
public class ELSEIF extends Token {
    public ELSEIF(TokenType type,String image) {
        super(type,image);
    }

}
