/* Generated by: JavaCC 21 Parser Generator. Do not edit. ELSEIF.java */
package qute;

@SuppressWarnings("unused")
public class ELSEIF extends Token {
    public ELSEIF(int kind,String image) {
        super(kind,image);
    }

}
