/* Generated by: JavaCC 21 Parser Generator. Do not edit. ELSE.java */
package qute;

@SuppressWarnings("unused")
public class ELSE extends Token {
    public ELSE(int kind,String image) {
        super(kind,image);
    }

}
