/* Generated by: JavaCC 21 Parser Generator. Do not edit. END_SECTION.java */
package qute;

public class END_SECTION extends Token {
    public END_SECTION(int kind,String image) {
        super(kind,image);
    }

}
