/* Generated by: JavaCC 21 Parser Generator. Do not edit. ENDEACH.java */
package qute;

@SuppressWarnings("unused")
public class ENDEACH extends Token {
    public ENDEACH(int kind,String image) {
        super(kind,image);
    }

}
