/* Generated by: JavaCC 21 Parser Generator. Do not edit. ENDEACH.java */
package qute;

@SuppressWarnings("unused")
public class ENDEACH extends Token {
    public ENDEACH(TokenType type,String image) {
        super(type,image);
    }

}
