/* Generated by: JavaCC 21 Parser Generator. Do not edit. ENDFOR.java */
package qute;

@SuppressWarnings("unused")
public class ENDFOR extends Token {
    public ENDFOR(TokenType type,String image) {
        super(type,image);
    }

}
