/* Generated by: JavaCC 21 Parser Generator. Do not edit. ENDINCLUDE.java */
package qute;

@SuppressWarnings("unused")
public class ENDINCLUDE extends Token {
    public ENDINCLUDE(int kind,String image) {
        super(kind,image);
    }

}
