/* Generated by: JavaCC 21 Parser Generator. Do not edit. ENDINCLUDE.java */
package qute;

@SuppressWarnings("unused")
public class ENDINCLUDE extends Token {
    public ENDINCLUDE(TokenType type,String image) {
        super(type,image);
    }

}
