/* Generated by: JavaCC 21 Parser Generator. Do not edit. ENDIF.java */
package qute;

public class ENDIF extends Token {
    public ENDIF(int kind,String image) {
        super(kind,image);
    }

}
