/* Generated by: JavaCC 21 Parser Generator. Do not edit. ENDIF.java */
package qute;

@SuppressWarnings("unused")
public class ENDIF extends Token {
    public ENDIF(TokenType type,String image) {
        super(type,image);
    }

}
