/* Generated by: JavaCC 21 Parser Generator. Do not edit. ENDINSERT.java */
package qute;

@SuppressWarnings("unused")
public class ENDINSERT extends Token {
    public ENDINSERT(TokenType type,String image) {
        super(type,image);
    }

}
