/* Generated by: JavaCC 21 Parser Generator. Do not edit. ENDINSERT.java */
package qute;

@SuppressWarnings("unused")
public class ENDINSERT extends Token {
    public ENDINSERT(int kind,String image) {
        super(kind,image);
    }

}
