/* Generated by: JavaCC 21 Parser Generator. Do not edit. ENDWITH.java */
package qute;

@SuppressWarnings("unused")
public class ENDWITH extends Token {
    public ENDWITH(TokenType type,String image) {
        super(type,image);
    }

}
