/* Generated by: JavaCC 21 Parser Generator. Do not edit. ENDWITH.java */
package qute;

@SuppressWarnings("unused")
public class ENDWITH extends Token {
    public ENDWITH(int kind,String image) {
        super(kind,image);
    }

}
