/* Generated by: JavaCC 21 Parser Generator. Do not edit. EQUALS3.java */
package qute;

@SuppressWarnings("unused")
public class EQUALS3 extends Token {
    public EQUALS3(TokenType type,String image) {
        super(type,image);
    }

}
