/* Generated by: JavaCC 21 Parser Generator. Do not edit. EQUALS2.java */
package qute;

@SuppressWarnings("unused")
public class EQUALS2 extends Token {
    public EQUALS2(int kind,String image) {
        super(kind,image);
    }

}
