/* Generated by: JavaCC 21 Parser Generator. Do not edit. EQUALS3.java */
package qute;

@SuppressWarnings("unused")
public class EQUALS3 extends Token {
    public EQUALS3(int kind,String image) {
        super(kind,image);
    }

}
