/* Generated by: JavaCC 21 Parser Generator. Do not edit. EQUALS.java */
package qute;

@SuppressWarnings("unused")
public class EQUALS extends Token {
    public EQUALS(TokenType type,String image) {
        super(type,image);
    }

}
