/* Generated by: JavaCC 21 Parser Generator. Do not edit. EXCLAM.java */
package qute;

@SuppressWarnings("unused")
public class EXCLAM extends Token {
    public EXCLAM(TokenType type,String image) {
        super(type,image);
    }

}
