/* Generated by: JavaCC 21 Parser Generator. Do not edit. FALSE.java */
package qute;

@SuppressWarnings("unused")
public class FALSE extends Token {
    public FALSE(int kind,String image) {
        super(kind,image);
    }

}
