/* Generated by: JavaCC 21 Parser Generator. Do not edit. FOR.java */
package qute;

@SuppressWarnings("unused")
public class FOR extends Token {
    public FOR(int kind,String image) {
        super(kind,image);
    }

}
