/* Generated by: JavaCC 21 Parser Generator. Do not edit. GE.java */
package qute;

@SuppressWarnings("unused")
public class GE extends Token {
    public GE(TokenType type,String image) {
        super(type,image);
    }

}
