/* Generated by: JavaCC 21 Parser Generator. Do not edit. GE.java */
package qute;

@SuppressWarnings("unused")
public class GE extends Token {
    public GE(int kind,String image) {
        super(kind,image);
    }

}
