/* Generated by: JavaCC 21 Parser Generator. Do not edit. GT.java */
package qute;

@SuppressWarnings("unused")
public class GT extends Token {
    public GT(TokenType type,String image) {
        super(type,image);
    }

}
