/* Generated by: JavaCC 21 Parser Generator. Do not edit. GT.java */
package qute;

@SuppressWarnings("unused")
public class GT extends Token {
    public GT(int kind,String image) {
        super(kind,image);
    }

}
