/* Generated by: JavaCC 21 Parser Generator. Do not edit. IF.java */
package qute;

@SuppressWarnings("unused")
public class IF extends Token {
    public IF(TokenType type,String image) {
        super(type,image);
    }

}
