/* Generated by: JavaCC 21 Parser Generator. Do not edit. IF.java */
package qute;

@SuppressWarnings("unused")
public class IF extends Token {
    public IF(int kind,String image) {
        super(kind,image);
    }

}
