/* Generated by: JavaCC 21 Parser Generator. Do not edit. IN.java */
package qute;

@SuppressWarnings("unused")
public class IN extends Token {
    public IN(TokenType type,String image) {
        super(type,image);
    }

}
