/* Generated by: JavaCC 21 Parser Generator. Do not edit. IN.java */
package qute;

@SuppressWarnings("unused")
public class IN extends Token {
    public IN(int kind,String image) {
        super(kind,image);
    }

}
