/* Generated by: JavaCC 21 Parser Generator. Do not edit. INSERT.java */
package qute;

@SuppressWarnings("unused")
public class INSERT extends Token {
    public INSERT(TokenType type,String image) {
        super(type,image);
    }

}
