/* Generated by: JavaCC 21 Parser Generator. Do not edit. INSERT.java */
package qute;

@SuppressWarnings("unused")
public class INSERT extends Token {
    public INSERT(int kind,String image) {
        super(kind,image);
    }

}
