/* Generated by: JavaCC 21 Parser Generator. Do not edit. INTEGER.java */
package qute;

@SuppressWarnings("unused")
public class INTEGER extends Token {
    public INTEGER(int kind,String image) {
        super(kind,image);
    }

}
