/* Generated by: JavaCC 21 Parser Generator. Do not edit. JSONString.java */
package qute;

@SuppressWarnings("unused")
public class JSONString extends Literal {
    public JSONString(TokenType type,String image) {
        super(type,image);
    }

}
