/* Generated by: JavaCC 21 Parser Generator. Do not edit. LE.java */
package qute;

@SuppressWarnings("unused")
public class LE extends Token {
    public LE(TokenType type,String image) {
        super(type,image);
    }

}
