/* Generated by: JavaCC 21 Parser Generator. Do not edit. LE.java */
package qute;

@SuppressWarnings("unused")
public class LE extends Token {
    public LE(int kind,String image) {
        super(kind,image);
    }

}
