/* Generated by: JavaCC 21 Parser Generator. Do not edit. Literal.java */
package qute;

@SuppressWarnings("unused")
public class Literal extends Token {
    public Literal(TokenType type,String image) {
        super(type,image);
    }

}
