/* Generated by: JavaCC 21 Parser Generator. Do not edit. Literal.java */
package qute;

@SuppressWarnings("unused")
public class Literal extends Token {
    public Literal(int kind,String image) {
        super(kind,image);
    }

}
