/* Generated by: JavaCC 21 Parser Generator. Do not edit. LT.java */
package qute;

@SuppressWarnings("unused")
public class LT extends Token {
    public LT(TokenType type,String image) {
        super(type,image);
    }

}
