/* Generated by: JavaCC 21 Parser Generator. Do not edit. MINUS.java */
package qute;

@SuppressWarnings("unused")
public class MINUS extends Token {
    public MINUS(int kind,String image) {
        super(kind,image);
    }

}
