/* Generated by: JavaCC 21 Parser Generator. Do not edit. MINUS.java */
package qute;

@SuppressWarnings("unused")
public class MINUS extends Token {
    public MINUS(TokenType type,String image) {
        super(type,image);
    }

}
