/* Generated by: JavaCC 21 Parser Generator. Do not edit. NULL.java */
package qute;

@SuppressWarnings("unused")
public class NULL extends Token {
    public NULL(int kind,String image) {
        super(kind,image);
    }

}
