/* Generated by: JavaCC 21 Parser Generator. Do not edit. NULL.java */
package qute;

@SuppressWarnings("unused")
public class NULL extends Token {
    public NULL(TokenType type,String image) {
        super(type,image);
    }

}
