/* Generated by: JavaCC 21 Parser Generator. Do not edit. NumberLiteral2.java */
package qute;

@SuppressWarnings("unused")
public class NumberLiteral2 extends Literal {
    public NumberLiteral2(int kind,String image) {
        super(kind,image);
    }

}
