/* Generated by: JavaCC 21 Parser Generator. Do not edit. NumberLiteral.java */
package qute;

@SuppressWarnings("unused")
public class NumberLiteral extends Literal {
    public NumberLiteral(int kind,String image) {
        super(kind,image);
    }

}
