/* Generated by: JavaCC 21 Parser Generator. Do not edit. OPEN_COMMENT.java */
package qute;

public class OPEN_COMMENT extends Token {
    public OPEN_COMMENT(int kind,String image) {
        super(kind,image);
    }

}
