/* Generated by: JavaCC 21 Parser Generator. Do not edit. OPEN_COMMENT.java */
package qute;

@SuppressWarnings("unused")
public class OPEN_COMMENT extends Token {
    public OPEN_COMMENT(TokenType type,String image) {
        super(type,image);
    }

}
