/* Generated by: JavaCC 21 Parser Generator. Do not edit. OPEN_BRACKET.java */
package qute;

@SuppressWarnings("unused")
public class OPEN_BRACKET extends Token {
    public OPEN_BRACKET(int kind,String image) {
        super(kind,image);
    }

}
