/* Generated by: JavaCC 21 Parser Generator. Do not edit. OPEN_BRACKET.java */
package qute;

@SuppressWarnings("unused")
public class OPEN_BRACKET extends Token {
    public OPEN_BRACKET(TokenType type,String image) {
        super(type,image);
    }

}
