/* Generated by: JavaCC 21 Parser Generator. Do not edit. OPEN_CURLY.java */
package qute;

@SuppressWarnings("unused")
public class OPEN_CURLY extends Token {
    public OPEN_CURLY(TokenType type,String image) {
        super(type,image);
    }

}
