/* Generated by: JavaCC 21 Parser Generator. Do not edit. OPEN_CURLY.java */
package qute;

public class OPEN_CURLY extends Token {
    public OPEN_CURLY(int kind,String image) {
        super(kind,image);
    }

}
