/* Generated by: JavaCC 21 Parser Generator. Do not edit. OR.java */
package qute;

@SuppressWarnings("unused")
public class OR extends Token {
    public OR(TokenType type,String image) {
        super(type,image);
    }

}
