/* Generated by: JavaCC 21 Parser Generator. Do not edit. OR.java */
package qute;

@SuppressWarnings("unused")
public class OR extends Token {
    public OR(int kind,String image) {
        super(kind,image);
    }

}
