/* Generated by: JavaCC 21 Parser Generator. Do not edit. OR2.java */
package qute;

@SuppressWarnings("unused")
public class OR2 extends Token {
    public OR2(TokenType type,String image) {
        super(type,image);
    }

}
