/* Generated by: JavaCC 21 Parser Generator. Do not edit. OR2.java */
package qute;

@SuppressWarnings("unused")
public class OR2 extends Token {
    public OR2(int kind,String image) {
        super(kind,image);
    }

}
