/* Generated by: JavaCC 21 Parser Generator. ParsingProblem.java */
package qute;

public class ParsingProblem {
    private Node location;
    private String inputSource;
    private String description;
    public String getInputSource() {
        if (inputSource!=null) {
            return inputSource;
        }
        if (location!=null&&location.getInputSource()!=null) {
            return location.getInputSource();
        }
        return"input";
    }

    public ParsingProblem(String description,Node location) {
        this.description=description;
        this.location=location;
    }

    public Node getNode() {
        return location;
    }
    
    public String getDescription() {
		return description;
	}

}
