/* Generated by: JavaCC 21 Parser Generator. Do not edit. PLUS.java */
package qute;

@SuppressWarnings("unused")
public class PLUS extends Token {
    public PLUS(TokenType type,String image) {
        super(type,image);
    }

}
