/* Generated by: JavaCC 21 Parser Generator. Do not edit. PLUS.java */
package qute;

@SuppressWarnings("unused")
public class PLUS extends Token {
    public PLUS(int kind,String image) {
        super(kind,image);
    }

}
