/* Generated by: JavaCC 21 Parser Generator. Do not edit. QUTEConstants.java */
package qute;

/**
 * Token literal values and constants.
 */
public interface QUTEConstants {
    int EOF=0;
    // End of file
    int ASCII_LETTER=2;
    int ASCII_DIGIT=3;
    int C_IDENTIFIER=4;
    int ESCAPE1=5;
    int ESCAPE2=6;
    int REGULAR_CHAR=7;
    int STRING_LITERAL=8;
    int ZERO=9;
    int NON_ZERO=10;
    int FRACTION=11;
    int EXPONENT=12;
    int NUMBER=13;
    int OPEN_PAREN=14;
    int CLOSE_PAREN=15;
    int NO_OPEN_CURLY=16;
    int ESCAPED_OPEN_CURLY=17;
    int WS=18;
    int TEXT=19;
    int OPEN_CURLY=20;
    int IF=21;
    int ENDIF=22;
    int ABBREVIATED_END=23;
    int ELSEIF=24;
    int ELSE=25;
    int START_SECTION=26;
    int END_SECTION=27;
    int OPEN_COMMENT=28;
    int CLOSE_COMMENT=30;
    int CLOSE_CURLY=31;
    int CLOSE_EMPTY=32;
    /**
   * Lexical States
   */
    int QUTE_TEXT=0;
    int QUTE_EXPRESSION=1;
    int IN_COMMENT=2;
    String[] tokenImage={"<EOF>","<1>","<ASCII_LETTER>","<ASCII_DIGIT>","<C_IDENTIFIER>","<ESCAPE1>","<ESCAPE2>","<REGULAR_CHAR>","<STRING_LITERAL>","\"0\"","<NON_ZERO>","<FRACTION>","<EXPONENT>","<NUMBER>","\"(\"","\")\"","<NO_OPEN_CURLY>","\"\\\\{\"","<WS>","<TEXT>","\"{\"","<IF>","\"{/if}\"","\"{/}\"","<ELSEIF>","<ELSE>","<START_SECTION>","<END_SECTION>","\"{!\"","<29>","\"!}\"","\"}\"","\"/}\"",};
    String[] nodeNames={"EOF","ASCII_LETTER","ASCII_DIGIT","C_IDENTIFIER","ESCAPE1","ESCAPE2","REGULAR_CHAR","STRING_LITERAL","ZERO","NON_ZERO","FRACTION","EXPONENT","NUMBER","OPEN_PAREN","CLOSE_PAREN","NO_OPEN_CURLY","ESCAPED_OPEN_CURLY","WS","TEXT","OPEN_CURLY","IF","ENDIF","ABBREVIATED_END","ELSEIF","ELSE","START_SECTION","END_SECTION","OPEN_COMMENT","CLOSE_COMMENT","CLOSE_CURLY","CLOSE_EMPTY","Expression","Parenthesis","Interpolation","IfBlock","ElseIfBlock","ElseBlock","Section","Block","Root",};
}
