/* Generated by: JavaCC 21 Parser Generator. Do not edit. QUTE_INCLUDE.java */
package qute;

@SuppressWarnings("unused")
public class QUTE_INCLUDE extends Token {
    public QUTE_INCLUDE(TokenType type,String image) {
        super(type,image);
    }

}
