/* Generated by: JavaCC 21 Parser Generator. Do not edit. RAW_STRING.java */
package qute;

@SuppressWarnings("unused")
public class RAW_STRING extends Token {
    public RAW_STRING(TokenType type,String image) {
        super(type,image);
    }

}
