/* Generated by: JavaCC 21 Parser Generator. Do not edit. RAW_STRING.java */
package qute;

@SuppressWarnings("unused")
public class RAW_STRING extends Token {
    public RAW_STRING(int kind,String image) {
        super(kind,image);
    }

}
