/* Generated by: JavaCC 21 Parser Generator. Do not edit. SIMPLE_EQUALS.java */
package qute;

@SuppressWarnings("unused")
public class SIMPLE_EQUALS extends Token {
    public SIMPLE_EQUALS(int kind,String image) {
        super(kind,image);
    }

}
