/* Generated by: JavaCC 21 Parser Generator. Do not edit. START_PARAMETER_DECL.java */
package qute;

@SuppressWarnings("unused")
public class START_PARAMETER_DECL extends Token {
    public START_PARAMETER_DECL(int kind,String image) {
        super(kind,image);
    }

}
