/* Generated by: JavaCC 21 Parser Generator. Do not edit. START_SECTION.java */
package qute;

@SuppressWarnings("unused")
public class START_SECTION extends Token {
    public START_SECTION(int kind,String image) {
        super(kind,image);
    }

}
