/* Generated by: JavaCC 21 Parser Generator. Do not edit. STRING_LITERAL.java */
package qute;

@SuppressWarnings("unused")
public class STRING_LITERAL extends Token {
    public STRING_LITERAL(int kind,String image) {
        super(kind,image);
    }

}
