/* Generated by: JavaCC 21 Parser Generator. Do not edit. StringLiteral.java */
package qute;

public class StringLiteral extends Literal {
    public StringLiteral(int kind,String image) {
        super(kind,image);
    }

}
