/* Generated by: JavaCC 21 Parser Generator. Do not edit. Text.java */
package qute;

@SuppressWarnings("unused")
public class Text extends Token {
    public Text(TokenType type,String image) {
        super(type,image);
    }

}
