/* Generated by: JavaCC 21 Parser Generator. Do not edit. TIMES.java */
package qute;

@SuppressWarnings("unused")
public class TIMES extends Token {
    public TIMES(int kind,String image) {
        super(kind,image);
    }

}
