/* Generated by: JavaCC 21 Parser Generator. Do not edit. TIMES.java */
package qute;

@SuppressWarnings("unused")
public class TIMES extends Token {
    public TIMES(TokenType type,String image) {
        super(type,image);
    }

}
