/* Generated by: JavaCC 21 Parser Generator. Token.java */
package qute;

/**
 * Describes the input token stream.
 */
public class Token implements QUTEConstants,Node {
    boolean virtual;
    public void setVirtual(boolean virtual) {
        this.virtual=virtual;
    }

    public boolean isDirty() {
        return this.virtual;
    }

    private String inputSource="";
    /**
     * An integer that describes the kind of this token.  This numbering
     * system is determined by JavaCCParser, and a table of these numbers is
     * stored in the file ...Constants.java.
     */
    int kind;
    /**
     * beginLine and beginColumn describe the position of the first character
     * of this token; endLine and endColumn describe the position of the
     * last character of this token.
     */
    int beginLine,beginColumn,endLine,endColumn;
    /**
     * The string image of the token.
     */
    String image;
    /**
     * A reference to the next regular (non-special) token from the input
     * stream.  If this is the last token from the input stream, or if the
     * token manager has not read tokens beyond this one, this field is
     * set to null.  This is true only if this token is also a regular
     * token.  Otherwise, see below for a description of the contents of
     * this field.
     */
    Token next;
    /**
     * This field is used to access special tokens that occur prior to this
     * token, but after the immediately preceding regular (non-special) token.
     * If there are no such special tokens, this field is set to null.
     * When there are more than one such special token, this field refers
     * to the last of these special tokens, which in turn refers to the next
     * previous special token through its specialToken field, and so on
     * until the first special token (whose specialToken field is null).
     * The next fields of special tokens refer to other special tokens that
     * immediately follow it (without an intervening regular token).  If there
     * is no such token, this field is null.
     */
    Token specialToken;
    private boolean unparsed;
    public Token() {
    }

    /**
     * Constructs a new token for the specified Image.
     */
    public Token(int kind) {
        this(kind,null);
    }

    /**
     * Constructs a new token for the specified Image and Kind.
     */
    public Token(int kind,String image) {
        this.kind=kind;
        this.image=image;
    }

    public int getId() {
        return kind;
    }

    public boolean isUnparsed() {
        return unparsed;
    }

    public void setUnparsed(boolean unparsed) {
        this.unparsed=unparsed;
    }

    public void clearChildren() {
    }

    public String getNormalizedText() {
        if (virtual) {
            return"Virtual Token";
        }
        return image;
    }

    public String getRawText() {
        return image;
    }

    public String toString() {
        return getNormalizedText();
    }

    public static Token newToken(int ofKind,String image) {
        switch(ofKind) {
            case C_IDENTIFIER:
            return new C_IDENTIFIER(ofKind,image);
            case STRING_LITERAL:
            return new StringLiteral(ofKind,image);
            case NUMBER:
            return new NumberLiteral(ofKind,image);
            case OPEN_PAREN:
            return new Delimiter(ofKind,image);
            case CLOSE_PAREN:
            return new Delimiter(ofKind,image);
            case TEXT:
            return new Text(ofKind,image);
            case OPEN_CURLY:
            return new OPEN_CURLY(ofKind,image);
            case IF:
            return new IF(ofKind,image);
            case ENDIF:
            return new ENDIF(ofKind,image);
            case ABBREVIATED_END:
            return new ABBREVIATED_END(ofKind,image);
            case ELSEIF:
            return new ELSEIF(ofKind,image);
            case ELSE:
            return new ELSE(ofKind,image);
            case START_SECTION:
            return new START_SECTION(ofKind,image);
            case END_SECTION:
            return new END_SECTION(ofKind,image);
            case OPEN_COMMENT:
            return new OPEN_COMMENT(ofKind,image);
            case CLOSE_COMMENT:
            return new Comment(ofKind,image);
            case CLOSE_CURLY:
            return new CLOSE_CURLY(ofKind,image);
            case CLOSE_EMPTY:
            return new CLOSE_EMPTY(ofKind,image);
        }
        return new Token(ofKind,image);
    }

    public void setInputSource(String inputSource) {
        this.inputSource=inputSource;
    }

    public String getInputSource() {
        return inputSource;
    }

    public void setBeginColumn(int beginColumn) {
        this.beginColumn=beginColumn;
    }

    public void setEndColumn(int endColumn) {
        this.endColumn=endColumn;
    }

    public void setBeginLine(int beginLine) {
        this.beginLine=beginLine;
    }

    public void setEndLine(int endLine) {
        this.endLine=endLine;
    }

    public int getBeginLine() {
        return beginLine;
    }

    public int getBeginColumn() {
        return beginColumn;
    }

    public int getEndLine() {
        return endLine;
    }

    public int getEndColumn() {
        return endColumn;
    }

    private Node parent;
    private java.util.Map<String,Object>attributes;
    @Override public boolean hasChildNodes() {
        return getChildCount()>0;
    }

    @Override public Node getFirstChild() {
        return Nodes.getFirstChild(this);
    }

    @Override public Node getLastChild() {
        return Nodes.getLastChild(this);
    }

    public void setChild(int i,Node n) {
        throw new UnsupportedOperationException();
    }

    public void addChild(Node n) {
        throw new UnsupportedOperationException();
    }

    public void addChild(int i,Node n) {
        throw new UnsupportedOperationException();
    }

    public Node removeChild(int i) {
        throw new UnsupportedOperationException();
    }

    public boolean removeChild(Node n) {
        return false;
    }

    public int indexOf(Node n) {
        return-1;
    }

    public Node getParent() {
        return parent;
    }

    public void setParent(Node parent) {
        this.parent=parent;
    }

    public int getChildCount() {
        return 0;
    }

    public Node getChild(int i) {
        return null;
    }

    public void open() {
    }

    public void close() {
    }

    public Object getAttribute(String name) {
        return attributes==null?null:
        attributes.get(name);
    }

    public void setAttribute(String name,Object value) {
        if (attributes==null) {
            attributes=new java.util.HashMap<String,Object>();
        }
        attributes.put(name,value);
    }

    public boolean hasAttribute(String name) {
        return attributes==null?false:
        attributes.containsKey(name);
    }

    public java.util.Set<String>getAttributeNames() {
        if (attributes==null) return java.util.Collections.emptySet();
        return attributes.keySet();
    }

    @Override public Node findNodeAt(int line,int column) {
        return Nodes.findNodeAt(this,line,column);
    }

}
