/* Generated by: JavaCC 21 Parser Generator. Do not edit. TRUE.java */
package qute;

@SuppressWarnings("unused")
public class TRUE extends Token {
    public TRUE(TokenType type,String image) {
        super(type,image);
    }

}
