/* Generated by: JavaCC 21 Parser Generator. Do not edit. WITH.java */
package qute;

@SuppressWarnings("unused")
public class WITH extends Token {
    public WITH(int kind,String image) {
        super(kind,image);
    }

}
